version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: materialize-css
    versions:
    - "> 0.98.2"
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - j0k3r
  - tcitworld
  - Kdecherf
  groups:
    babel-dependencies:
      patterns:
        - "*babel*"
    fontsource-dependencies:
      patterns:
        - "*fontsource*"
  ignore:
  - dependency-name: lcobucci/jwt
    versions:
    - ">= 4.2.0"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
