version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: materialize-css
    versions:
    - "> 0.98.2"
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - j0k3r
  - tcitworld
  - Kdecherf
  labels:
  - Ready for review
  ignore:
  - dependency-name: doctrine/doctrine-migrations-bundle
    versions:
    - "> 1.3.2"
  - dependency-name: friendsofsymfony/user-bundle
    versions:
    - "> 2.0.2"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
