language: php

# faster builds on docker-container setup
sudo: false

# used for HHVM
addons:
  apt:
    packages:
      - tidy

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

matrix:
    fast_finish: true
    exclude:
        - php: hhvm
          env: DB=pgsql  # driver for PostgreSQL currently unsupported by HHVM, requires 3rd party dependency
    allow_failures:
        - php: hhvm

# exclude v1 branches
branches:
    except:
        - master
        - dev

before_script:
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi;
    - composer self-update --no-progress
<<<<<<< e645fc1a1f2e8bac3497b79ffe8343b88ca3d2a5
    - if [[ "$DB" = "pgsql" ]]; then psql -c 'create database wallabag_test;' -U postgres; fi;

before_install:
    - if [[ $TRAVIS_REPO_SLUG = wallabag/wallabag ]]; then cp .composer-auth.json ~/.composer/auth.json; fi;
=======
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - if [[ "$DB" = "pgsql" ]]; then psql -c 'create database wallabag_test;' -U postgres; fi;
>>>>>>> Fix postgres database creation

before_install:
    - if [[ $TRAVIS_REPO_SLUG = wallabag/wallabag ]]; then cp .composer-auth.json ~/.composer/auth.json; fi;

script:
    - travis_wait composer update --no-interaction --no-progress
    - ant prepare-$DB
    - bin/phpunit -v
