language: php

# faster builds on docker-container setup
sudo: false

# used for HHVM
addons:
  apt:
    packages:
      - tidy

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

matrix:
    fast_finish: true
    exclude:
        - php: hhvm
          env: DB=pgsql  # driver for PostgreSQL currently unsupported by HHVM, requires 3rd party dependency
    allow_failures:
        - php: hhvm

# exclude v1 branches
branches:
    except:
        - master
        - dev

before_script:
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi;
    - composer self-update --no-progress
<<<<<<< bd561aeb66e1b67a8db188042fbe6d556564341d
<<<<<<< 5898b243c3b009fdaa2684db94411fe8a5a94696
<<<<<<< e645fc1a1f2e8bac3497b79ffe8343b88ca3d2a5
=======
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> Add the timezone as an argument in the docker-compose. For that, need to use v2 of docker-compose (with version >= 1.6.0)
    - if [[ "$DB" = "pgsql" ]]; then psql -c 'create database wallabag_test;' -U postgres; fi;

before_install:
    - if [[ $TRAVIS_REPO_SLUG = wallabag/wallabag ]]; then cp .composer-auth.json ~/.composer/auth.json; fi;
=======
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
=======
<<<<<<< bd561aeb66e1b67a8db188042fbe6d556564341d
>>>>>>> Defining Github token is now useless
    - if [[ "$DB" = "pgsql" ]]; then psql -c 'create database wallabag_test;' -U postgres; fi;
>>>>>>> Fix postgres database creation
=======
>>>>>>> 97c5746... Defining Github token is now useless
    - if [[ "$DB" = "pgsql" ]]; then psql -c 'create database wallabag_test;' -U postgres; fi;
>>>>>>> 2648ce1... Fix postgres database creation
>>>>>>> Add the timezone as an argument in the docker-compose. For that, need to use v2 of docker-compose (with version >= 1.6.0)

before_install:
    - if [[ $TRAVIS_REPO_SLUG = wallabag/wallabag ]]; then cp .composer-auth.json ~/.composer/auth.json; fi;

before_install:
    - if [[ $TRAVIS_REPO_SLUG = wallabag/wallabag ]]; then cp .composer-auth.json ~/.composer/auth.json; fi;

script:
    - travis_wait composer update --no-interaction --no-progress
    - ant prepare-$DB
    - bin/phpunit -v
