wallabag_comment:
  type : rest
  resource: "@WallabagCommentBundle/Resources/config/routing_comments.yml"

wallabag_import:
    resource: "@WallabagImportBundle/Controller/"
    type:     annotation
    prefix:   /import

wallabag_api:
    resource: "@WallabagApiBundle/Resources/config/routing.yml"
    prefix: /

app:
    resource: "@WallabagCoreBundle/Controller/"
    type: annotation

doc-api:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc

rest :
    type : rest
    resource : "routing_rest.yml"
    prefix : /api

homepage:
    path: "/{page}"
    defaults:
        _controller: WallabagCoreBundle:Entry:showUnread
        page : 1
    requirements:
        page: \d+

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

craue_config_settings_modify:
    path: /settings
    defaults:
        _controller: CraueConfigBundle:Settings:modify
