wallabag_api:
    resource: "@WallabagApiBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @WallabagCoreBundle/Controller/
    type:     annotation

doc-api:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc

login:
    pattern:   /login
    defaults:  { _controller: WallabagCoreBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    path:   /logout

rest :
    type : rest
    resource : "routing_rest.yml"
    prefix : /api

homepage:
    pattern:   "/{page}"
    defaults:  { _controller: WallabagCoreBundle:Entry:showUnread, page : 1 }
    requirements:
        page:  \d+

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

wallabag_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: WallabagCoreBundle:Security:oauthLogin }

wallabag_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: WallabagCoreBundle:Security:loginCheck }
