security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity:
                class: WallabagUserBundle:User
                property: username
        fos_userbundle:
            id: fos_user.user_provider.username

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

        api:
            pattern: /api/.*
            fos_oauth: true
            stateless: true
            anonymous: true

        login_firewall:
            pattern: "^%base_path%/login$"
            anonymous:  ~

        secured_area:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                check_path: "%base_path%/login_check"
                login_path: "%base_path%/login"
                default_target_path: "%base_path%/"

            anonymous: true
            remember_me:
                secret: "%secret%"
                lifetime: 31536000
                path: "%base_path%/"
                domain: ~

            logout:
                path:   "%base_path%/logout"
                target: "%base_path%/"

    access_control:
        - { path: "^%base_path%/api/doc", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%base_path%/api/version", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%base_path%/login", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%base_path%/register", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%base_path%/resetting", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "%base_path%/(unread|starred|archive).xml$", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%base_path%/settings", roles: ROLE_SUPER_ADMIN }
        - { path: "^%base_path%/annotations", roles: ROLE_USER }
        - { path: "^%base_path%/", roles: ROLE_USER }
