parameters:
    lexik_form_filter.get_filter.doctrine_orm.class: Wallabag\CoreBundle\Event\Subscriber\CustomDoctrineORMSubscriber

services:
    # used for tests
    filesystem_cache:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments:
            - %kernel.cache_dir%/doctrine/metadata

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    wallabag.twig_extension:
        class: Wallabag\CoreBundle\Twig\WallabagExtension
        public: false
        tags:
            - { name: twig.extension }

    wallabag.twig_piwik_extension:
        class: PiwikTwigExtension\PiwikTwigExtension
        public: false
        tags:
            - { name: twig.extension }

    wallabag.locale_listener:
        class: Wallabag\CoreBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    wallabag.user_locale_listener:
        class: Wallabag\CoreBundle\EventListener\UserLocaleListener
        arguments: ["@session"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
