# RabbitMQ stuff
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Wallabag\ImportBundle\Consumer\RabbitMQConsumerTotalProxy:
        lazy: true
        arguments:
            $pocketConsumer: '@old_sound_rabbit_mq.import_pocket_consumer'
            $readabilityConsumer: '@old_sound_rabbit_mq.import_readability_consumer'
            $wallabagV1Consumer: '@old_sound_rabbit_mq.import_wallabag_v1_consumer'
            $wallabagV2Consumer: '@old_sound_rabbit_mq.import_wallabag_v2_consumer'
            $firefoxConsumer: '@old_sound_rabbit_mq.import_firefox_consumer'
            $chromeConsumer: '@old_sound_rabbit_mq.import_chrome_consumer'
            $instapaperConsumer: '@old_sound_rabbit_mq.import_instapaper_consumer'
            $pinboardConsumer: '@old_sound_rabbit_mq.import_pinboard_consumer'
            $deliciousConsumer: '@old_sound_rabbit_mq.import_delicious_consumer'
            $elcuratorConsumer: '@old_sound_rabbit_mq.import_elcurator_consumer'
            $omnivoreConsumer: '@old_sound_rabbit_mq.import_omnivore_consumer'
            $shaarliConsumer: '@old_sound_rabbit_mq.import_shaarli_consumer'
            $pocketHtmlConsumer: '@old_sound_rabbit_mq.import_pocket_html_consumer'

    wallabag_import.consumer.amqp.pocket:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\PocketImport'

    wallabag_import.consumer.amqp.readability:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\ReadabilityImport'

    wallabag_import.consumer.amqp.instapaper:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\InstapaperImport'

    wallabag_import.consumer.amqp.pinboard:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\PinboardImport'

    wallabag_import.consumer.amqp.delicious:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\DeliciousImport'

    wallabag_import.consumer.amqp.omnivore:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\OmnivoreImport'

    wallabag_import.consumer.amqp.wallabag_v1:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\WallabagV1Import'

    wallabag_import.consumer.amqp.wallabag_v2:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\WallabagV2Import'

    wallabag_import.consumer.amqp.elcurator:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\ElcuratorImport'

    wallabag_import.consumer.amqp.firefox:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\FirefoxImport'

    wallabag_import.consumer.amqp.chrome:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\ChromeImport'

    wallabag_import.consumer.amqp.shaarli:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\ShaarliImport'

    wallabag_import.consumer.amqp.pocket_html:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            $import: '@Wallabag\ImportBundle\Import\PocketHtmlImport'
