jms_serializer:
    visitors:
        json_serialization:
            options:
                - JSON_PRETTY_PRINT
                - JSON_UNESCAPED_SLASHES
                - JSON_PRESERVE_ZERO_FRACTION
