parameters:
    fosuser_registration: true
    wallabag_dbname_suffix: '_test'

services:
    filesystem_cache:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments:
            - "%kernel.cache_dir%/doctrine/metadata"

    # fixtures
    Wallabag\DataFixtures\:
        resource: '../fixtures/*'
        tags: ['doctrine.fixture.orm']
        autowire: true
