# RabbitMQ stuff
services:
    wallabag_import.consumer.amqp.pocket:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_user.user_repository"
            - "@wallabag_import.pocket.import"
            - "@logger"
    wallabag_import.consumer.amqp.readability:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_user.user_repository"
            - "@wallabag_import.readability.import"
            - "@logger"
    wallabag_import.consumer.amqp.wallabag_v1:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_user.user_repository"
            - "@wallabag_import.wallabag_v1.import"
            - "@logger"
    wallabag_import.consumer.amqp.wallabag_v2:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_user.user_repository"
            - "@wallabag_import.wallabag_v2.import"
            - "@logger"
    wallabag_import.consumer.amqp.firefox:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_user.user_repository"
            - "@wallabag_import.firefox.import"
            - "@logger"
    wallabag_import.consumer.amqp.chrome:
        class: Wallabag\ImportBundle\Consumer\AMQPEntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_user.user_repository"
            - "@wallabag_import.chrome.import"
            - "@logger"
