services:
    wallabag_import.consumer.entry:
        class: Wallabag\ImportBundle\Component\AMPQ\EntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_core.entry_repository"
            - "@wallabag_core.content_proxy"

    wallabag_import.chain:
        class: Wallabag\ImportBundle\Import\ImportChain

    wallabag_import.pocket.client:
        class: GuzzleHttp\Client
        arguments:
            -
                defaults:
                    headers:
                        content-type: "application/json"
                        X-Accept: "application/json"

    wallabag_import.pocket.import:
        class: Wallabag\ImportBundle\Import\PocketImport
        arguments:
            - "@security.token_storage"
            - "@doctrine.orm.entity_manager"
            - "@wallabag_core.content_proxy"
            - "@craue_config"
            - %rabbitmq%
            - "@old_sound_rabbit_mq.wallabag_producer"
        calls:
            - [ setClient, [ "@wallabag_import.pocket.client" ] ]
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: pocket }

    wallabag_import.wallabag_v1.import:
        class: Wallabag\ImportBundle\Import\WallabagV1Import
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_core.content_proxy"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: wallabag_v1 }

    wallabag_import.wallabag_v2.import:
        class: Wallabag\ImportBundle\Import\WallabagV2Import
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_core.content_proxy"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: wallabag_v2 }
