services:
    wallabag_import.consumer.pocket:
        class: Wallabag\ImportBundle\Consumer\AMPQ\EntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_user.user_repository"
            - "@wallabag_import.pocket.import"
            - "@logger"
    wallabag_import.consumer.readability:
        class: Wallabag\ImportBundle\Consumer\AMPQ\EntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_user.user_repository"
            - "@wallabag_import.readability.import"
            - "@logger"
    wallabag_import.consumer.wallabag_v1:
        class: Wallabag\ImportBundle\Consumer\AMPQ\EntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_user.user_repository"
            - "@wallabag_import.wallabag_v1.import"
            - "@logger"
    wallabag_import.consumer.wallabag_v2:
        class: Wallabag\ImportBundle\Consumer\AMPQ\EntryConsumer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_user.user_repository"
            - "@wallabag_import.wallabag_v2.import"
            - "@logger"

    wallabag_import.chain:
        class: Wallabag\ImportBundle\Import\ImportChain

    wallabag_import.pocket.client:
        class: GuzzleHttp\Client
        arguments:
            -
                defaults:
                    headers:
                        content-type: "application/json"
                        X-Accept: "application/json"

    wallabag_import.pocket.import:
        class: Wallabag\ImportBundle\Import\PocketImport
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_core.content_proxy"
            - "@craue_config"
        calls:
            - [ setClient, [ "@wallabag_import.pocket.client" ] ]
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: pocket }

    wallabag_import.wallabag_v1.import:
        class: Wallabag\ImportBundle\Import\WallabagV1Import
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_core.content_proxy"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: wallabag_v1 }

    wallabag_import.wallabag_v2.import:
        class: Wallabag\ImportBundle\Import\WallabagV2Import
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_core.content_proxy"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: wallabag_v2 }

    wallabag_import.readability.import:
        class: Wallabag\ImportBundle\Import\ReadabilityImport
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_core.content_proxy"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: readability }
