imports:
    - { resource: rabbit.yml }
    - { resource: redis.yml }

services:
    wallabag_import.chain:
        class: Wallabag\ImportBundle\Import\ImportChain

    wallabag_import.pocket.client:
        class: GuzzleHttp\Client
        arguments:
            -
                defaults:
                    headers:
                        content-type: "application/json"
                        X-Accept: "application/json"

    wallabag_import.pocket.import:
        class: Wallabag\ImportBundle\Import\PocketImport
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_core.content_proxy"
            - "@craue_config"
        calls:
            - [ setClient, [ "@wallabag_import.pocket.client" ] ]
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: pocket }

    wallabag_import.wallabag_v1.import:
        class: Wallabag\ImportBundle\Import\WallabagV1Import
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_core.content_proxy"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: wallabag_v1 }

    wallabag_import.wallabag_v2.import:
        class: Wallabag\ImportBundle\Import\WallabagV2Import
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_core.content_proxy"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: wallabag_v2 }

    wallabag_import.readability.import:
        class: Wallabag\ImportBundle\Import\ReadabilityImport
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_core.content_proxy"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: readability }

    wallabag_import.browser.import:
        class: Wallabag\ImportBundle\Import\BrowserImport
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@wallabag_core.content_proxy"
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: wallabag_import.import, alias: browser }
