services:
    wallabag_core.helper.detect_active_theme:
        class: Wallabag\CoreBundle\Helper\DetectActiveTheme
        arguments:
            - @security.context
            - %theme% # default theme from parameters.yml

    # custom form type
    wallabag_core.form.type.config:
        class: Wallabag\CoreBundle\Form\Type\ConfigType
        arguments:
            - %liip_theme.themes%
        tags:
            - { name: form.type, alias: config }

    wallabag_core.form.registration:
        class: Wallabag\CoreBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: wallabag_user_registration }

    wallabag_core.form.type.forgot_password:
        class: Wallabag\CoreBundle\Form\Type\ForgotPasswordType
        arguments:
            - @doctrine
        tags:
            - { name: form.type, alias: forgot_password }

    wallabag_core.param_converter.username_rsstoken_converter:
        class: Wallabag\CoreBundle\ParamConverter\UsernameRssTokenConverter
        tags:
            - { name: request.param_converter, converter: username_rsstoken_converter }
        arguments:
            - @doctrine

    wallabag_core.doctrine.prefixed_naming_strategy:
        class: Wallabag\CoreBundle\Doctrine\Mapping\PrefixedNamingStrategy
        arguments:
            - %database_table_prefix%

    wallabag_core.graby:
        class: Graby\Graby
        arguments:
            - { error_message: false }

    wallabag_core.content_proxy:
        class: Wallabag\CoreBundle\Helper\ContentProxy
        arguments:
            - @wallabag_core.graby

    wallabag_core.registration_confirmed:
        class: Wallabag\CoreBundle\EventListener\RegistrationConfirmedListener
        arguments:
            - @doctrine.orm.entity_manager
            - %theme%
            - %items_on_page%
            - %rss_limit%
            - %language%
        tags:
            - { name: kernel.event_subscriber }
