name: "Assets"

on:
  pull_request:
  push:
    branches:
      - master
      - 2.*

permissions:
  contents: read

jobs:
  js:
    name: "Building assets"
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install Node"
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: "Install dependencies with Yarn"
        run: "yarn install"

      - name: "Build dev assets"
        run: "yarn run build:dev"

      - name: "Build prod assets"
        run: "yarn run build:prod"

      - name: "Validate no change were created"
        run: |
          GITDIFF=`git diff`
          if [ "$GITDIFF" == "" ]; then
            exit 0
          else
            git diff
            exit 1
          fi
